### PR TITLE
Make FillMode and StrokeMode components

### LINKED ISSUE #162: Improve ergonomics of DrawMode
It's currently very annoying to update `DrawMode` because you need to do something if the enum variant doesn't match your expectations even though you know the variant can only ever be X. A better design IMO is to delete DrawMode and turn FillMode + StrokeMode into components. This naturally expresses the idea that they can be ORed together.

### PR DESCRIPTION
**Pull request by rparrett**
Opening for discussion. IMO, this change feels pretty good in action.

Fixes #162

### CODE REVIEW

**Comment by Nilirad** [comment]
I like the fact that it significantly simplifies its usage, especially on the `dynamic_shape` example. It also looks more idiomatic, from Bevy's perspective.

**Comment by rparrett** [comment]
Ah right, I need to fix up a bunch of docs.

What do you think about `Fill` and `Stroke` vs `FillMode` and `StrokeMode`

**Comment by Nilirad** [comment]
> What do you think about `Fill` and `Stroke` vs `FillMode` and `StrokeMode`

Just had the same thoughts about it. Now that they are components, `Fill` and `Stroke` seem more appropriate.

**Comment by rparrett** [comment]
This currently makes spawning shapes at non-default transforms, or spawning invisible shapes a bit less ergonomic:
```rust
// Probably the best way
commands.spawn((
    ShapeBundle {
        transform: Transform::from_xyz(100., 0., 0.),
        ..GeometryBuilder::build_as(&line)
    },
    StrokeMode::new(Color::BLACK, 10.0),
));

// Spawn-and-insert would probably not be considered bevy best-practice
commands
    .spawn((
        GeometryBuilder::build_as(&line),
        StrokeMode::new(Color::BLACK, 10.0),
    ))
    .insert(Visibility::Hidden);
```

Maybe `GeometryBuilder` should return a `Path` rather than a `ShapeBundle`. (Seems like `PathBuilder` already works this way?)

```
commands.spawn((
    ShapeBundle {
        path: GeometryBuilder::build_as(&line),
        transform: Transform::from_xyz(100., 0., 0.),
    },
    StrokeMode::new(Color::BLACK, 10.0),
));
```

Let me know what you think.

**Comment by Nilirad** [comment]
I agree, I think it's better to let users build their own bundles instead of giving them a pre-made one that needs to be edited after.

**Comment by rparrett** [comment]
I took the liberty to make `path.rs` slightly more visually interesting and include a custom transform so there's at least one of those in the examples.

**Comment by Nilirad** [comment]
LGTM!

I originally created the path example as a “test”, since it broke once without notice, so I'm glad that now it displays something more appealing than a line.

**Pull request merged**
